name: exinity_assessment
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  get_it: 7.7.0
  injectable: 2.4.4
  flutter_bloc: 8.1.6
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  web_socket_channel: ^3.0.1
  dio: 5.7.0
  fpdart: ^1.1.0
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: 2.6.2
  json_serializable: 6.8.0
  freezed: 2.5.7
  build_runner: 2.4.12
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  bloc_test: ^9.1.7
  mocktail: ^1.0.4


flutter:

  assets:
   - .env


  uses-material-design: true

